import "./globals.css";
import { Providers } from "./providers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overscroll-none">
        <Providers>
          <div className="bg-gradient-to-r from-background to-secondary-background text-on-background">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
